apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
  namespace: demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springbootcontainer
        image: singhragvendra503/springboot:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: database
        - name: MONGO_DB_PASSWORD
          value: db@1234
---
apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
  namespace: demo-ns
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongorc
  namespace: demo-ns
spec:
  selector:
    app: mongodb
  template:
    metadata:
      name: mongo
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongocontainer
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: database
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: db@1234
          volumeMounts:
          - name: mangovolume
            mountPath: /data/db
      volumes:
      - name: mangovolume
        hostPath:
          path: /mongodatabase
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: demo-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017


