apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ayush2107/nodde:1.0
        ports:
        - containerPort: 80



---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100



# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
# spec:
#   selector:
#     app: webapp
#   ports:
#     - port: 80
#       targetPort: 80
#   type: LoadBalancer

